### PR TITLE
Add scss-lint.yml

### PR DESCRIPTION
**Pull request by davleh**
@ain @GeorgMeyer23 @beroes 
Together with Max (our new freelancer) I tried to define a more complete declaration order specification for SCSS-linting. I added new blocks for transforms, transitions and animations to have a better overview over all animation properties applied to an element. Please have a look and feel free to discuss!

### CODE REVIEW

**Comment by ain** [comment]
We need to give it a spin on a legacy project where the old style convention has been used. @beroes if you have time, please it a run on SHFE. The way @davidyezsetz built it up for well-reasoned so we need to make sure that we maintain current status and look into improving it rather than remaking it.

**Comment by davleh** [comment]
I tried to keep the structure @davidyezsetz suggested, but added some specifications in between, that absolutely make sense to my opinion. Flex box and animation properties are getting more and more important, so we should definitely consider them in our structure. I don't think we will get a lot of conflicts with the old configuration. We could use tools like CSScomb to manage the structure in our IDE, there is also a grunt plugin that we could use to easily reorder the css legacy code if needed.

**Comment by davleh** [comment]
I put a block of css functions at the top at first, perhaps that is something we should overthink with a view to out legacy code. I removed this from the suggested configuration.

- content
- quotes
- counter-reset
- counter-increment

**Comment by ain** [comment]
Sounds good :)

**Comment by GeorgMeyer23** [comment]
I don't see that we have legacy support, since old projects are running on their config.
I like the Idea of extending this to the actual state of the art css.

**Comment by davleh** [comment]
@GeorgMeyer23 Conflicts resolved. Now mergeable.

**Pull request merged**
